Added colour command
LeggoMyEcho/DrawBot pull request #9
Opened 2016-11-20 17:49 UTC by Cyan101

2016-11-20 17:50 UTC, Cyan101 commented
should also probably rename the file to responses.rb, i'd do this myself but im not sure if this file is referenced anywhere else in the code

2016-11-20 17:52 UTC, z64 commented
@Cyan101 the files are lazily included and not bound by filename ; it uses my modular bot template

2016-11-21 02:50 UTC, Cyan101 commented
Renamed the file for simplicity and so it matches the database

2016-11-21 15:17 UTC, z64 requested changes
Please add the `:color` command as well.

2016-11-21 15:17 UTC, z64 commented on lib/modules/commands/responses.rb
> +        thing = thing.join(' ')
This does not exist, nor is it used for anything

2016-11-21 15:17 UTC, z64 commented on lib/modules/commands/responses.rb
> +        event.message.delete
I would prefer for us not to delete invoking messages for things like this where data is returned. For actions it makes sense, for this, it doesn't.

2016-11-21 18:05 UTC, closed without merging